export default {
  PAYMENT_LIST_LOADING: "PAYMENT_LIST_LOADING",
  PAYMENT_LIST_SUCCESS: "PAYMENT_LIST_SUCCESS",
  PAYMENT_LIST_ERROR: "PAYMENT_LIST_ERROR",
  PAYMENT_INFO_LOADING: "PAYMENT_INFO_LOADING",
  PAYMENT_INFO_SUCCESS: "PAYMENT_INFO_SUCCESS",
  PAYMENT_INFO_ERROR: "PAYMENT_INFO_ERROR",
  SETTLE_PAYMENT_LOADING: "SETTLE_PAYMENT_LOADING",
  SETTLE_PAYMENT_SUCCESS: "SETTLE_PAYMENT_SUCCESS",
  SETTLE_PAYMENT_ERROR: "SETTLE_PAYMENT_ERROR",
};
