export default {
  COUNTRIES_ENUMERATES_LOADING: "COUNTRIES_ENUMERATES_LOADING",
  COUNTRIES_ENUMERATES_SUCCESS: "COUNTRIES_ENUMERATES_SUCCESS",
  COUNTRIES_ENUMERATES_ERROR: "COUNTRIES_ENUMERATES_ERROR",

  CURRENCIES_ENUMERATES_LOADING: "CURRENCIES_ENUMERATES_LOADING",
  CURRENCIES_ENUMERATES_SUCCESS: "CURRENCIES_ENUMERATES_SUCCESS",
  CURRENCIES_ENUMERATES_ERROR: "CURRENCIES_ENUMERATES_ERROR",

  TIMEZONES_ENUMERATES_LOADING: "TIMEZONES_ENUMERATES_LOADING",
  TIMEZONES_ENUMERATES_SUCCESS: "TIMEZONES_ENUMERATES_SUCCESS",
  TIMEZONES_ENUMERATES_ERROR: "TIMEZONES_ENUMERATES_ERROR",
};
