export default {
  EMPLOYEE_LIST_LOADING: "EMPLOYEE_LIST_LOADING",
  EMPLOYEE_LIST_SUCCESS: "EMPLOYEE_LIST_SUCCESS",
  EMPLOYEE_LIST_ERROR: "EMPLOYEE_LIST_ERROR",
  EMPLOYEE_INFO_LOADING: "EMPLOYEE_INFO_LOADING",
  EMPLOYEE_INFO_SUCCESS: "EMPLOYEE_INFO_SUCCESS",
  EMPLOYEE_INFO_ERROR: "EMPLOYEE_INFO_ERROR",
  SETTLE_SALARY_LOADING: "SETTLE_SALARY_LOADING",
  SETTLE_SALARY_SUCCESS: "SETTLE_SALARY_SUCCESS",
  SETTLE_SALARY_ERROR: "SETTLE_SALARY_ERROR",
};
