export default {
  COMPANY_LIST_LOADING: "COMPANY_LIST_LOADING",
  COMPANY_LIST_SUCCESS: "COMPANY_LIST_SUCCESS",
  COMPANY_LIST_ERROR: "COMPANY_LIST_ERROR",
  COMPANY_INFO_LOADING: "COMPANY_INFO_LOADING",
  COMPANY_INFO_SUCCESS: "COMPANY_INFO_SUCCESS",
  COMPANY_INFO_ERROR: "COMPANY_INFO_ERROR",
};
